version: "3"
# ╔═════════════════════════════════════╗
# ║ Services                            ║
# ╚═════════════════════════════════════╝
services:
# ╔═════════════════════════════════════╗
# ║ gestsup
# ╚═══════════════╝
  gestsup:
    build:
      context: .
      args:
        PHP_VERSION: "8.2"
        GESTSUP_VERSION: "3.2.40"
    ports:
      - 3010:80
    depends_on:
      - mariadb
    volumes:
      - ./html:/var/www/html/
    networks:
      - gestsup
# ╔═══════════════╗
# ║ gestsup
# ╚═════════════════════════════════════╝
# ╔═════════════════════════════════════╗
# ║ mariadb
# ╚═══════════════╝
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_DATABASE: bsup
      MYSQL_USER: gestsup
      MYSQL_PASSWORD: CHANGEME
    restart: on-failure
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - gestsup
# ╔═══════════════╗
# ║ mariadb
# ╚═════════════════════════════════════╝
# ╔═════════════════════════════════════╗
# ║ volumes
# ╚═══════════════╝
volumes:
  html: {}
  mysql: {}
# ╔═══════════════╗
# ║ volumes
# ╚═════════════════════════════════════╝
# ╔═════════════════════════════════════╗
# ║ networks
# ╚═══════════════╝
networks:
  gestsup:
# ╔═══════════════╗
# ║ networks
# ╚═════════════════════════════════════╝
